### PR TITLE
Paginate section pins

### PR DESCRIPTION
**Pull request by anonymustard**
The docstring for get_section_pins says to call it repeatedly to get all of the pins in the section, but that can't work without BookmarkManager

### CODE REVIEW

**Comment by bstoilov** [comment]
Thank you for spotting and fixing this

**Comment by imgVOID** [comment]
while section_pins:
    for sec_pin in section_pins:
    print(sec_pin['id'])
    section_pins = pinterest.get_section_pins(section_id=section['id'])

**Comment by imgVOID** [comment]
In my case 'while' is endless, but all pins have been collected.

**Comment by imgVOID** [comment]
I've made 'for' without 'while' on 56 pins section, and it's obtaining all the pins corectly too. wtf

**Pull request merged**
